<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <!--
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

        </style>
            -->
        <link type="text/css" rel="stylesheet" href="../node_modules/bootstrap/dist/css/bootstrap.min.css"/>
        <link type="text/css" rel="stylesheet" href="../node_modules/bootstrap/dist/css/bootstrap-theme.min.css"/>
        <link type="text/css" rel="stylesheet" href="../node_modules/bootstrap/dist/css/bootstrap.min.css"/>
        <link type="text/css" rel="stylesheet" href="../node_modules/fullcalendar/dist/fullcalendar.min.css"/>
        <link type="text/css" rel="stylesheet" href="../node_modules/fullcalendar/dist/fullcalendar.print.min.css"/>
        <link type="text/css" rel="stylesheet" href="../lib/css/common.css"/>

        <script type="text/javascript" src="../node_modules/fullcalendar/node_modules/moment/moment.js"></script>
        <script type="text/javascript" src="../node_modules/fullcalendar/node_modules/moment/moment.js"></script>
        <script type="text/javascript" src="../node_modules/jquery/dist/jquery.min.js"></script>
        <script type="text/javascript" src="../lib/js/clock.js"></script>
        <script type="text/javascript" src="../node_modules/bootstrap/dist/js/bootstrap.min.js"></script>
        <script type="text/javascript" src="../node_modules/fullcalendar/dist/fullcalendar.min.js"></script>
        <script type="text/javascript" src="../node_modules/fullcalendar/dist/locale/ja.js"></script>
    </head>
    <body>
        <h1><img src="../images/logo_mottainai.png" alt="mottainai" height="100px" /></h1>

        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <div class="row">
                        <div class="col-md-12">
                            <h2>時刻</h2>
                        </div>
                    </div>
                    <ul class="clock">
                        <li><div class="hour"></div></li>
                        <li>:</li>
                        <li><div class="min"></div></li>
                        <li>:</li>
                        <li><div class="second"></div></li>
                    </ul>
                    <br>
                    <div class="row">
                        <div class="col-md-12">
                            <h2>今月のゴミ廃棄量</h2>
                        </div>
                    </div>
                    <div class="row top-trash nama">
                        <a href="graph.php">
                            <div class="col-md-7">生ゴミ</div>
                            <div class="col-md-5 tar">13,098g</div>
                        </a>
                    </div>
                    <div class="row top-trash">
                        <div class="col-md-7">燃えるゴミ</div>
                        <div class="col-md-5 tar">5,442g</div>
                    </div>
                    <div class="row top-trash">
                        <div class="col-md-7">燃えないゴミ</div>
                        <div class="col-md-5 tar">2,895g</div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div id="calendar">
                        <script>
                            $("#calendar").fullCalendar({
                                aditable: true
                            });
                        </script>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>
