<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <!--
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

        </style>
            -->
        <link type="text/css" rel="stylesheet" href="../node_modules/bootstrap/dist/css/bootstrap.min.css"/>
        <link type="text/css" rel="stylesheet" href="../node_modules/bootstrap/dist/css/bootstrap-theme.min.css"/>
        <link type="text/css" rel="stylesheet" href="../node_modules/bootstrap/dist/css/bootstrap.min.css"/>
        <link type="text/css" rel="stylesheet" href="../node_modules/fullcalendar/dist/fullcalendar.min.css"/>
        <link type="text/css" rel="stylesheet" href="../node_modules/fullcalendar/dist/fullcalendar.print.min.css"/>
        <link type="text/css" rel="stylesheet" href="../lib/css/common.css"/>

        <script type="text/javascript" src="../node_modules/fullcalendar/node_modules/moment/moment.js"></script>
        <script type="text/javascript" src="../node_modules/fullcalendar/node_modules/moment/moment.js"></script>
        <script type="text/javascript" src="../node_modules/jquery/dist/jquery.min.js"></script>
        <script type='text/javascript' src='https://www.gstatic.com/charts/loader.js'></script>
        <script src="https://d3js.org/d3.v4.min.js"></script>
        <script type="text/javascript" src="../lib/js/clock.js"></script>
        <!--script type="text/javascript" src="../lib/js/draw.js"></script-->
        <script type="text/javascript" src="../node_modules/bootstrap/dist/js/bootstrap.min.js"></script>
        <script type="text/javascript" src="../node_modules/fullcalendar/dist/fullcalendar.min.js"></script>
        <script type="text/javascript" src="../node_modules/fullcalendar/dist/locale/ja.js"></script>
        <script type="text/javascript" src="//maps.google.com/maps/api/js?key=AIzaSyDRWYvrGuFzBbiuoEvN-dTPXYsYYzAGASE"></script>
        <script type="text/javascript" src="../lib/js/googlemap.js"></script>

        <script type="text/javascript">
        /*
        function initialize() {
        var latlng = new google.maps.LatLng(-34.397, 150.644);
        var myOptions = {
        zoom: 8,
        center: latlng,
        mapTypeId: google.maps.MapTypeId.ROADMAP
        };
        var map = new google.maps.Map(document.getElementById('map_canvas'), myOptions);
        }
        */
        </script>
        <script type='text/javascript'>
         google.charts.load('current', {
           'packages': ['geochart'],
           // Note: you will need to get a mapsApiKey for your project.
           // See: https://developers.google.com/chart/interactive/docs/basic_load_libs#load-settings
           'mapsApiKey': 'AIzaSyAaPe-eoiK1_zHIl56SvnXtNbzeQmNc12A'
         });
         google.charts.setOnLoadCallback(drawMarkersMap);

          function drawMarkersMap() {
          var data = google.visualization.arrayToDataTable([
            ['City',   '', 'Area'],
            ['Osaka',     2761477,    1285.31],
            ['Milan',     1324110,    181.76],
            ['Naples',    959574,     117.27],
            ['Turin',     907563,     130.17],
            ['Palermo',   655875,     158.9],
            ['Genoa',     607906,     243.60],
            ['Bologna',   380181,     140.7],
            ['Florence',  371282,     102.41],
            ['Fiumicino', 67370,      213.44],
            ['Anzio',     52192,      43.43],
            ['Ciampino',  38262,      11]
          ]);

        var options = {
            zoom: 15,
            region: 'JP',
            displayMode: 'markers',
            colorAxis: {colors: ['#33aa33', '#aa3333']}
        };

          var chart = new google.visualization.GeoChart(document.getElementById('chart_div'));
          chart.draw(data, options);
        };
        </script>

    </head>
    <body onload="initialize();">
        <h1><img src="../images/logo_mottainai.png" alt="mottainai" height="100px" /></h1>

        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <div class="row">
                        <div class="col-md-12">
                            <h2>時刻</h2>
                        </div>
                    </div>
                    <ul class="clock">
                        <li><div class="hour"></div></li>
                        <li>:</li>
                        <li><div class="min"></div></li>
                        <li>:</li>
                        <li><div class="second"></div></li>
                    </ul>
                    <br>
                    <div class="row">
                        <div class="col-md-12">
                            <h2>今月のゴミ廃棄量</h2>
                        </div>
                    </div>
                    <div class="row top-trash nama">
                        <a href="graph.php">
                            <div class="col-md-7">生ゴミ</div>
                            <div class="col-md-5 tar">13,098g</div>
                        </a>
                    </div>
                    <div class="row top-trash">
                        <div class="col-md-7">燃えるゴミ</div>
                        <div class="col-md-5 tar">5,442g</div>
                    </div>
                    <div class="row top-trash">
                        <div class="col-md-7">燃えないゴミ</div>
                        <div class="col-md-5 tar">2,895g</div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div id="calendar">
                        <script>
                            $("#calendar").fullCalendar({
                                aditable: true
                            });
                        </script>
                    </div>
                </div>
                <div class="row">
                    <div id="map-canvas" style="width:100%;height:480px;"></div>
                </div>
                <div class="row">
                    <div id="chart_div" style="width: 100%; height: 500px;"></div>
                </div>
            </div>
        </div>
        <div class="container" style="height:100px;">
            Copyright 2017 Mottainai Project
        </div>
    </body>
</html>
